### ISSUE TITLE
Fix This

### ISSUE THREAD

**Issue by Zoryn4163** [yuukiw/StardewValleyMM#1]
Do dynamic searching or something. This, this is unacceptable.
https://github.com/yuukiw/StardewValleyMM/blob/master/WindowsApplication1/MainForm.vb#L188

If (Not System.IO.File.Exists(Application.UserAppDataPath & "\SDVNN.ini")) Then
            If (Not System.IO.Directory.Exists("C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley")) Then
                If (Not System.IO.Directory.Exists("C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley")) Then
                    If (Not System.IO.Directory.Exists("E:\Program Files (x86)\Steam\steamapps\common\Stardew Valley")) Then
                        If (Not System.IO.Directory.Exists("C:\Games\Stardew Valley")) Then
                            If (Not System.IO.Directory.Exists("D:\Games\Stardew Valley")) Then
                                If (Not System.IO.Directory.Exists("E:\Games\Stardew Valley")) Then
                                    INI()
                                Else
                                    folder = "E:\Games\Stardew Valley"
                                    gog = 1
                                    INI_WriteValueToFile("General", "GameFolder", folder, Application.UserAppDataPath & "\SDVNN.ini")
                                    INI_WriteValueToFile("General", "SteamFolder", Sfolder, Application.UserAppDataPath & "\SDVNN.ini")
                                    INI_WriteValueToFile("General", "Good Old Game Version", gog, Application.UserAppDataPath & "\SDVNN.ini")
                                End If
                            Else
                                folder = "D:\Games\Stardew Valley"
                                gog = 1
                                INI_WriteValueToFile("General", "GameFolder", folder, Application.UserAppDataPath & "\SDVNN.ini")
                                INI_WriteValueToFile("General", "SteamFolder", Sfolder, Application.UserAppDataPath & "\SDVNN.ini")
                                INI_WriteValueToFile("General", "Good Old Game Version", gog, Application.UserAppDataPath & "\SDVNN.ini")
                            End If
                        Else
                            folder = "C:\Games\Stardew Valley"
                            gog = 1
                            INI_WriteValueToFile("General", "GameFolder", folder, Application.UserAppDataPath & "\SDVNN.ini")
                            INI_WriteValueToFile("General", "SteamFolder", Sfolder, Application.UserAppDataPath & "\SDVNN.ini")
                            INI_WriteValueToFile("General", "Good Old Game Version", gog, Application.UserAppDataPath & "\SDVNN.ini")
                        End If
                    Else
                        folder = "E:\Program Files (x86)\Steam\steamapps\common\Stardew Valley"
                        Sfolder = "E:\Program Files (x86)\Steam"
                        INI_WriteValueToFile("General", "GameFolder", folder, Application.UserAppDataPath & "\SDVNN.ini")
                        INI_WriteValueToFile("General", "SteamFolder", Sfolder, Application.UserAppDataPath & "\SDVNN.ini")
                        INI_WriteValueToFile("General", "Good Old Game Version", gog, Application.UserAppDataPath & "\SDVNN.ini")
                    End If
                Else
                    folder = "D:\Program Files (x86)\Steam\steamapps\common\Stardew Valley"
                    Sfolder = "D:\Program Files (x86)\Steam"
                    INI_WriteValueToFile("General", "GameFolder", folder, Application.UserAppDataPath & "\SDVNN.ini")
                    INI_WriteValueToFile("General", "SteamFolder", Sfolder, Application.UserAppDataPath & "\SDVNN.ini")
                    INI_WriteValueToFile("General", "Good Old Game Version", gog, Application.UserAppDataPath & "\SDVNN.ini")
                End If
            Else
                folder = "C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley"
                Sfolder = "C:\Program Files (x86)\Steam"
                INI_WriteValueToFile("General", "GameFolder", folder, Application.UserAppDataPath & "\SDVNN.ini")
                INI_WriteValueToFile("General", "SteamFolder", Sfolder, Application.UserAppDataPath & "\SDVNN.ini")
                INI_WriteValueToFile("General", "Good Old Game Version", gog, Application.UserAppDataPath & "\SDVNN.ini")
            End If
            INI_WriteValueToFile("SMAPI Details", "Version", "SMAPI_0.37.1A", Application.UserAppDataPath & "\SDVNN.ini")
        Else
            folder = INI_ReadValueFromFile("General", "GameFolder", "C:\", Application.UserAppDataPath & "\SDVNN.ini")
            Sfolder = INI_ReadValueFromFile("General", "SteamFolder", "C:\", Application.UserAppDataPath & "\SDVNN.ini")
            gog = INI_ReadValueFromFile("General", "Good Old Game Version", 0, Application.UserAppDataPath & "\SDVNN.ini")
            cSVersion = INI_ReadValueFromFile("SMAPI Details", "Version", "SMAPI_0.37.1A", Application.UserAppDataPath & "\SDVNN.ini")
        End If

**Comment by yuukiw** [comment]
I agree that this is quite a sloby way if looking for an file and I will improve it ASAP.

**Comment by yuukiw** [comment]
i rewrote it quite a bit. It should be much better now and also more oriented towards all kinds of HArdware configurations. I didnt want to do an full on crawl since this would make the start up very long depending on the amount of files on the drives.

What is you opinion about the changes?

**Comment by Zoryn4163** [comment]
Definitely an improvement, thank you.

**Comment by yuukiw** [comment]
if you see any other code piece that doesnt look ok just say so.
