### ISSUE TITLE
Some mods are loaded twice for some players

### ISSUE THREAD

**Issue by Pathoschild** [yuukiw/StardewValleyMM#10]
I've seen several users with mods loaded from both `%appdata%/Stardew Valley/Mods` and `<install path>/Mods`, which tends to break mods. I don't use the mod manager myself, so I'm not sure what situation this happens in. 

Known cases if you want to look into it:

| user | log |
| :-- | :-- |
| [Domas](http://www.nexusmods.com/stardewvalley/users/2082608/) via [Nexus Mods bug](http://www.nexusmods.com/stardewvalley/mods/541/?tab=14&navtag=/stardewvalley/ajax/modbugs/%3Fid%3D541%26openreport%3D187280) | [2016-10-26 domas log.txt](https://github.com/yuukiw/StardewValleyMM/files/554865/2016-10-26.domas.log.txt) |

**Comment by yuukiw** [comment]
should be fixed with removing of the appdata support with moving all mods to the gamefoler, too.
