### ISSUE TITLE
No longer add mods to AppData for SMAPI 1.0 compatibility

### ISSUE THREAD

**Issue by Pathoschild** [yuukiw/StardewValleyMM#11]
The upcoming SMAPI 1.0 release will no longer recognise mods installed in `%appdata%\StardewValley\Mods`, and will only recognise the standard `<game install path>/Mods` folder (see ClxS/SMAPI#156).

Please update the mod manager to only add mods under the game folder. (If the mod manager could move its existing mods from AppData too, that'd be very useful for your users.)

**Comment by yuukiw** [comment]
fixed in 16dea26ae156271cef6537e19a193ffdfdf2965b

**Comment by Pathoschild** [comment]
Thanks! Could you update [the build on Nexus Mods](http://www.nexusmods.com/stardewvalley/mods/21)?

**Comment by yuukiw** [comment]
done

**Comment by Pathoschild** [comment]
Thanks! :)
