### ISSUE TITLE
Defaults to C:\ directory without telling user

### ISSUE THREAD

**Issue by RoboGH** [yuukiw/StardewValleyMM#12]
When I first started the mod manager, it defaulted to the C:\ directory as the game directory and tried to install SMAPI to it. This should probably be changed to require the user to point to the game folder before the prompt to install SMAPI.
My steam install directory is a non-default location, in case that matters.

**Comment by yuukiw** [comment]
Thats interesting since it Should open the Settings form if it cant find the game in either the steam folder or in the usual GOG Folder.

Did it give any message Box prior to wanting to install Smapi?

**Comment by RoboGH** [comment]
Yes, first it prompted me for installing the new update for the mod manager (2.7a to 2.8).
You may want to update the latest release on GitHub for that, by the way.

**Comment by yuukiw** [comment]
I would lie if i would say that i know the exact reason of it happening but i added an last checks that looks for the games exe in the path it thinks the game is located before he moves any files around. 

This hopefully will fix this issue.

**Comment by yuukiw** [comment]
44c2b0e38d1dfeec6d4190a0433eb7866fe2fc88
