### ISSUE TITLE
Every time "Refresh" is clicked on the SMAPI Mods tab all XNB mods are duplicated

### ISSUE THREAD

**Issue by RoboGH** [yuukiw/StardewValleyMM#13]
This doesn't create new files, just entries.
After pressing it twice:

![sdvmm issue](https://cloud.githubusercontent.com/assets/23618764/20466378/34aa8776-af40-11e6-8fff-34e103ea0d71.PNG)

Restarting the Manager fixes the issue until Refresh is pressed again.

**Comment by yuukiw** [comment]
could you post the xnb ini ?
(settings - open ini folder)

**Comment by RoboGH** [comment]
Here you go:

[XNB Backup paths]
Animal Sprite - Calico Cat - cat.xnb=D:\Games\Steam\SteamApps\common\Stardew Valley\Content\Animals\cat.xnb
Animal Sprite - Bordercollie Dog - dog..xnb=D:\Games\Steam\SteamApps\common\Stardew Valley\Content\Animals\dog.xnb
Character Sprite - Genderswap Alex - Alex.xnb=D:\Games\Steam\SteamApps\common\Stardew Valley\Content\Characters\Alex.xnb
Character Sprite - Genderswap Wizard - Wizard.xnb=D:\Games\Steam\SteamApps\common\Stardew Valley\Content\Characters\Wizard.xnb
Portrait - Genderswap Wizard - Wizard.xnb=D:\Games\Steam\SteamApps\common\Stardew Valley\Content\Portraits\Wizard.xnb
Portrait - Genderswap Alex - Alex.xnb=D:\Games\Steam\SteamApps\common\Stardew Valley\Content\Portraits\Alex.xnb

**Comment by yuukiw** [comment]
and it adds another entry everytime you press refresh?

**Comment by RoboGH** [comment]
Yeah, here it is after pressing several times:

![capture](https://cloud.githubusercontent.com/assets/23618764/20466541/30c8c264-af43-11e6-9e13-4f3d37dc9796.PNG)

**Comment by yuukiw** [comment]
okay. Silly error on my end. Forgot the add an check against double entries in the xnb part of the code. 
Did the update fix it?

**Comment by RoboGH** [comment]
It doesn't seem to want to update. It says my version is 2.8b. Is that correct?

**Comment by yuukiw** [comment]
[SDVMM.zip](https://github.com/yuukiw/StardewValleyMM/files/602378/SDVMM.zip)

**Comment by RoboGH** [comment]
Yes, that fixed it.
