### ISSUE TITLE
It is impossible to add XNB mods

### ISSUE THREAD

**Issue by Tondorian** [yuukiw/StardewValleyMM#14]
If you try to add a ContentMod it adds an " " into the path and throws an fileNotFoundException

**Comment by yuukiw** [comment]
could you link the mod?

**Comment by Tondorian** [comment]
I tried this one:
http://www.nexusmods.com/stardewvalley/mods/137/?tab=2&navtag=http%3A%2F%2Fwww.nexusmods.com%2Fstardewvalley%2Fajax%2Fmodfiles%2F%3Fid%3D137&pUp=1 

here is the error output: 
![errormessage](https://cloud.githubusercontent.com/assets/1161281/21965710/aa36b41e-db65-11e6-9466-16abc40b0257.PNG)

**Comment by yuukiw** [comment]
ok working on it, found the error.

**Comment by Tondorian** [comment]
thank you for this fix works fine now
