### ISSUE TITLE
WindowsApplication1 has stopped working.

### ISSUE THREAD

**Issue by Sqwrly** [yuukiw/StardewValleyMM#15]
SDVMM has worked fine in the past. I opened it today and it told me there was an update for it as well as the API. I updated and now when I try to run SDVMM I just get a windows error message saying "WindowsApplication1 has stopped working" "A problem caused the program to stop working correctly. Please close the program." It has only one button that says "Close the program" and that's all that I get. This is on 3.1c. I redownloaded 3.1b and 3.1 but get the same error with those.

Windwos 10 Pro x64 with all latest updates
i7 4970k
16GB DDR3
250GB SSD
Geforce 980Ti

**Comment by yuukiw** [comment]
could you try the newest version from here?
http://www.nexusmods.com/stardewvalley/mods/21/?tab=2&navtag=http%3A%2F%2Fwww.nexusmods.com%2Fstardewvalley%2Fajax%2Fmodfiles%2F%3Fid%3D21&pUp=1

**Comment by Sqwrly** [comment]
Same result. :(

**Comment by yuukiw** [comment]
could you check if your AV put sdvmm in quarantine?

**Comment by Sqwrly** [comment]
I don't run any AV, including Windows defender. The SDVMM exe file never moves either.

**Comment by yuukiw** [comment]
could you backup and remove everything in here %appdata%\SDVMM\WindowsApplication1\1.0.0.0

**Comment by Sqwrly** [comment]
Same result. I also just tried removing the %appdata%\SDVMM folder entirely, same thing.

**Comment by yuukiw** [comment]
could you make a image of the folder where sdvmm is in?

**Comment by Sqwrly** [comment]
At this point the folder is empty since I deleted it all and started from scratch. http://i.imgur.com/YCNIwL5.png

**Comment by yuukiw** [comment]
does it start now through?
btw interesting explorer, which one do you use?

**Comment by Sqwrly** [comment]
I tried uninstalling Stardew altogether and made sure to delete the Stardew folder in the steamapps/common dir. Deleted SDVMM in %appdata% so it should all be fresh. Still doesn't start, same error.

My explorer is Dirctory Opus. :)

**Comment by yuukiw** [comment]
https://drive.google.com/file/d/0B94u0_R6vixWTmZ1QS11WlgyVXM/view?usp=sharing does this build atleast give a more precise error?

**Comment by Sqwrly** [comment]
It does! http://i.imgur.com/YtQbWOD.png

I manually created the folder it complained about then it did the same for 'deactivatedMods' then again for the 'Backup' folder where SDVMM.exe sits. After that it started and said SMAPI wasn't installed. I told it to install then it said there was an update to SMAPI, then when I told it to update I received this error: http://i.imgur.com/p9M7e05.png

edit* when I clicked retry it said the same thing about SMAPI not being installed then asked if I wanted to update then threw this error: http://i.imgur.com/8jBA7UH.png

**Comment by yuukiw** [comment]
which sdvmm version was that?

**Comment by Sqwrly** [comment]
That was using the special build from your google drive.

**Comment by yuukiw** [comment]
could you try again? i just tested it, he complains the first time but actually creates the files it wants and laucnhed the second time.

**Comment by Sqwrly** [comment]
which exe should I be using?

**Comment by yuukiw** [comment]
the one i gave you

**Comment by Sqwrly** [comment]
Getting a new error. When I ran it it said SMAPI wasn't installed and then said it needed to be updated, when I said yes to update I got this: http://i.imgur.com/YsKBHMN.png

If I click through the errors a second time it opens SDVMM. The steam and Stardew folders weren't set in the settings. When I set those and hit save I received an Unhandled exception.

http://i.imgur.com/yFMioct.png

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '-1' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ListBox.ObjectCollection.get_Item(Int32 index)
   at SDVMM.MainForm.ModList_tooltip(Object sender, EventArgs e)
   at System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
SDVMM
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/bin/Stardew/SDVMM.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Deployment
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.1.19813
    CodeBase: file:///C:/bin/Stardew/Newtonsoft.Json.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1636.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Sqwrly** [comment]
I clicked continue on that and restarted SDVMM and it seems to be ok now.

*edit* I take that back. Still some minor issues. Anytime I try to disable a mod I receive and unhandled exception. Activating a mod seems ok though.

**Comment by yuukiw** [comment]
i found the issue and already made a fix. in the meantime just open the settings and add the correct paths

**Comment by Sqwrly** [comment]
See my edit in the last post. I still get an error when disabling mods. I can paste the unhandled exception details if you need.

**Comment by yuukiw** [comment]
The issue is arrising due SDVMM not having the acutall path where the game is residing. you can provide it in the setting.

**Comment by Sqwrly** [comment]
I have both directories setup in settings already. It still throws the exception when disabling mods.

http://i.imgur.com/hroKToz.png

**Comment by yuukiw** [comment]
ok thanks. the issue was the newly added tooltip.
https://drive.google.com/file/d/0B94u0_R6vixWTmZ1QS11WlgyVXM/view?usp=sharing

**Comment by Sqwrly** [comment]
That build still throws the exception. It also tells me there is an update to SDVMM. It tells me there is an update even after I update, every time. If I use that build and tell it not to update it still throws the error.

**Comment by yuukiw** [comment]
ah my error. it seems i forgot to build the new release binary and due this i uploaded the old 3.1c file which resulted in a loop.

update shoudl work now.

**Comment by Sqwrly** [comment]
It all seems fixed now. I really appreciate your work on this and your quick response. Thank you!

**Comment by yuukiw** [comment]
no problem^^
