### ISSUE TITLE
Not recognizing dll files

### ISSUE THREAD

**Issue by Jiggynant** [yuukiw/StardewValleyMM#3]
I'm trying to add a smapi dll but when I click the button it doesn't recognize the dll file.

**Comment by yuukiw** [comment]
what did you mean with recognize? that he doesnt show them?
If so just change xnb to smapi

**Comment by Jiggynant** [comment]
I mean that when I try to add a smapi mod by clicking the "Add smapi/xnb Mod" I can't find the dll file at its file location.

**Comment by yuukiw** [comment]
like i said just change the mode in the field right over open/cancel.

(dont know why it default to xnb through)

**Comment by Jiggynant** [comment]
Ah, thanks. Sorry for the confusion

**Comment by yuukiw** [comment]
no problem
