### ISSUE TITLE
SDVMM - Unhandled Exception Occurred/Unable to read file

### ISSUE THREAD

**Issue by KiraWolfDragon** [yuukiw/StardewValleyMM#4]
Ok, so I started up SDVMM and it gave me a message saying:

Unhandled exception has occurred in your application. Click continue/quit, blah, blah. Access to the path Desktop\SDVMM\Updater.exe is denied

And whenever I try to add mods, It says Unable to read file from disk! Please restart SDVMM and try again.

I dont know if I should try a different release. Im running 1.4g and I can post the error log i get from the first error I get when I start the application if I need to. Id really like to be able to use this for mods, and it doesnt give the version information for SDVMM or SMAPI down at the bottom like it is supposed to.

**Comment by yuukiw** [comment]
could you post the log?

**Comment by yuukiw** [comment]
I mostlikely found the issue. I forgot to change a line.

**Comment by KiraWolfDragon** [comment]
Here is the full log it gives me when I launch the Mod Manager for version 1.4g

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.UnauthorizedAccessException: Access to the path 'C:\Users\drago\Downloads\SDVMM\Updater.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at SDVMM.MainForm.CheckVersion(String Version)
   at SDVMM.MainForm.SDVMM_Startup()
   at SDVMM.MainForm._Lambda$__3(Object a0, EventArgs a1)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1073.0 built by: NETFXREL3STAGE

##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

SDVMM
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0

##     CodeBase: file:///C:/Users/drago/Downloads/SDVMM/SDVMM.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.6.1038.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Deployment
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by yuukiw** [comment]
ok then this was another issue.

I just checked again and it seems i just missnamed the update file.

**Comment by yuukiw** [comment]
could you check if there is an updater.exe @C:\Users\drago\Downloads\SDVMM\  , if so try deleting it.
It seems like he finds the file but cant delete it.

**Comment by KiraWolfDragon** [comment]
Sorry about the late reply to the thread, but I tried deleting it, and when I deleted it, i launched SDVMM, it tries to open, recreates the updater and then crashes

**Comment by yuukiw** [comment]
how does sdvmm react when you install the update manually (via executing the updater.exe) and then delete it and start the programm?

**Comment by KiraWolfDragon** [comment]
Oh, running the updater worked :) I dont get the startup message, but Ill check when I add the mods later. If I have anymore issues, Ill let you know ^^ Thanks for the help~

**Comment by MemorablePink** [comment]
yuukiw, I wanna ask, how do I uninstall SDVMM? My SDVMM seem to be having problem and I want to uninstall it and reinstall again.

**Comment by yuukiw** [comment]
just delete the exe.
and the inis.

**Comment by MemorablePink** [comment]
I tried but it keep on come back =/..

**Comment by yuukiw** [comment]
what exactly is happening?

**Comment by MemorablePink** [comment]
I tried to install it, then it appears this topic title issue. After that, I tried launching but nothing works and I end up wasted 1 day by pressing P and skipped 1 of my day.
Then I went to delete the files off, but it just can't be removed. After I delete, it will be recovered again. I'm not sure why. I'm seeking for a solution =/.

**Comment by yuukiw** [comment]
what exactly gets recovered?

**Comment by MemorablePink** [comment]
the files being deleted recovered after being deleted

**Comment by yuukiw** [comment]
what kind of files?
also did you delete the ini files in the appdata folder?

**Comment by MemorablePink** [comment]
the SVDMM? That Backup and Update and also those Updater.exe and etc.

**Comment by yuukiw** [comment]
and the update.exe always comes back?
if so just execute it the update manually.
