### ISSUE TITLE
An exception has occured

### ISSUE THREAD

**Issue by Jiggynant** [yuukiw/StardewValleyMM#5]
When I start the mod manager I get an error saying: An exception has occured in your application software. If you click on continue this problem will be ignored. If you click close the program will be closed immediately.

Object variable or With Block variable has not been defined

System.NullReferenceException: Object variable or With Block variable has not been defined
   vid Microsoft.VisualBasic.CompilerServices.Symbols.Container..ctor(Object Instance)
   vid Microsoft.VisualBasic.CompilerServices.NewLateBinding.LateGet(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack)
   vid SDVMM.MainForm.checkSmapiUpdate()
   vid SDVMM.MainForm.SDVMM_Startup()
   vid SDVMM.MainForm._Lambda$__1(Object a0, EventArgs a1)
   vid System.Windows.Forms.Form.OnShown(EventArgs e)
   vid System.Windows.Forms.Form.CallShownEvent()
   vid System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   vid System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   vid System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   vid System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   vid System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Comment by Jiggynant** [comment]
It cleans the entire modlist every startup as well

**Comment by yuukiw** [comment]
the "cleaning" is normal since he has to parse all mods on launch

**Comment by Jiggynant** [comment]
So having the modlist completely whiped and readding everything every startup is normal?

**Comment by yuukiw** [comment]
they should be there once he done with "starting" through, or are they gone for good?

**Comment by Jiggynant** [comment]
As I said, I get an error at launch and it whipes the modlist if I chose to hit continue and ignore the exception.

**Comment by yuukiw** [comment]
ah it seems he skip the entire sub. Will try to find the error.

**Comment by yuukiw** [comment]
could you run that file and tell me the error code (if any appears)

[SDVMM.zip](https://github.com/yuukiw/StardewValleyMM/files/187777/SDVMM.zip)

**Comment by Jiggynant** [comment]
Failed to launch: Error Code 8

**Comment by yuukiw** [comment]
OK thanks. Will try to solve it. But it could be tricky since i cant reproduce it but i will do my best

**Comment by Jiggynant** [comment]
If it helps I also noticed that at the bottom of the client it doesn't display the mod manager/SMAPI version info it just says SDVMM Version Info, SMAPI Version Info. Don't know if that's any different of what should be displayed.

**Comment by yuukiw** [comment]
and that one? 

[SDVMM.zip](https://github.com/yuukiw/StardewValleyMM/files/187889/SDVMM.zip)

**Comment by Jiggynant** [comment]
Yeah, that one fixed it.
