### ISSUE TITLE
1.6 not reading smapi mods

### ISSUE THREAD

**Issue by Jiggynant** [yuukiw/StardewValleyMM#6]
Since the latest version the launcher is not loading any smapi mods. I've tried restarting, readding and reinstalling the client but the smapi launcher. Not sure if this is a smapi issue or the mod manager. The manager is set to the stardew valley folder and not appdata so not sure why it's not working.

Some mod were duplications on the list and when trying to delete those mods from modlist I get the error message: Can not convert type FileInfo to type String

System.InvalidCastException: Can not convert type FileInfo to type String
   vid Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   vid SDVMM.MainForm.delm_Click(Object sender, EventArgs e)
   vid System.Windows.Forms.Control.OnClick(EventArgs e)
   vid System.Windows.Forms.Button.OnClick(EventArgs e)
   vid System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   vid System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   vid System.Windows.Forms.Control.WndProc(Message& m)
   vid System.Windows.Forms.ButtonBase.WndProc(Message& m)
   vid System.Windows.Forms.Button.WndProc(Message& m)
   vid System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   vid System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   vid System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by yuukiw** [comment]
smapi changed its system as this you need to delete all mods and wait for the mod creator to update their mods (smapi only) and then just install it with the sdvmm

**Comment by Jiggynant** [comment]
I can't delete all the mods from the launcher though as it throws this error when I try to.

**Comment by yuukiw** [comment]
delete them manually.

**Comment by Jiggynant** [comment]
I have deleted them completely, still shows up on the Activated mod list and gives the error if I try to remove it from the launcher

**Comment by yuukiw** [comment]
is the storm.ini empty too?

**Comment by Jiggynant** [comment]
Except from the 3 default configuration files yes

**Comment by yuukiw** [comment]
could you send an picture of the the activated list?

**Comment by Jiggynant** [comment]
http://i.imgur.com/gulZH4u.png

**Comment by Jiggynant** [comment]
I'm unable to delete the simplesprinkler/SJB, that's when the error message shows up

**Comment by yuukiw** [comment]
interesting "content" shouldnt even appear.

**Comment by Jiggynant** [comment]
This is using the latest version you released 15 hours ago

**Comment by Jiggynant** [comment]
Also when I restart the launcher there's 2 Simple sprinkler under activated mods, one which I can delete. One which I can't, whenever I restart it the first one reappears.

**Comment by yuukiw** [comment]
could you upload your mod folder?
I want to try to reproduce it.

**Comment by Jiggynant** [comment]
I found what caused it, the mods were also put in the appdata/mods folder so I also deleted them from there and now they're not in the list anymore

**Comment by Jiggynant** [comment]
It's still not loading any mods though even though I got the latest version which should work with newest smapi: https://github.com/ADoby/SimpleSprinkler/releases/. still says 0 mods loaded

**Comment by Jiggynant** [comment]
Okay, I got it working. What I had done was put the dll file alone in a folder without its manifest so what it did was create a copy of whatever else was in that folder as its config file. When I put the folder itself and read it from there it then worked.

**Comment by Jiggynant** [comment]
Thanks for helping, this time it ended up me being an idiot as to why it wasn't working.

**Comment by Jiggynant** [comment]
Did you remove the ability to select multiple items in the latest version btw? When I try to select multple portraits for example i can only select one at a time.

**Comment by yuukiw** [comment]
seems so ^^"
Thanks, i accidently set the wrong option to false.
