### ISSUE TITLE
[SDVMM Version 1.6b] ISSUE - All update-related messages lead to exceptions

### ISSUE THREAD

**Issue by NeedyMonster** [yuukiw/StardewValleyMM#7]
Hello YuukiW,

My issue is essentially the same as others, save for something else no-one else seems to notice.

Here are some criteria I tested under:
- Run as and not as administrator
- Deleted update and backup files every 2 attempts

I will first say that if I try to Yes to everything (SMAPI and it's update), I will get a error stating that it cannot read from my disk, error level 2. It then goes to an exception. 
Running the app afterwards and attempting to install or update SMAPI in any way will simply say that one of the necessary files exists, then state that it cannot connect to the internet and causes an exception afterwards.

The second is that regardless of what happens, you will get an exception at the end. I chose no to all choices and got an exception. I've asked to install SMAPI and not update and got an exception.

Choosing to continue after an exception doesn't seem to have any drawbacks. SMAPI remains uninstalled and I can seem to launch Stardew Valley fine.

Feel free to ask for any information you may need.
- Needy

**Comment by yuukiw** [comment]
i reworked the update routine for Smapi , hopefully this fixed it.

**Comment by yuukiw** [comment]
could you test that file
[SDVMM.zip](https://github.com/yuukiw/StardewValleyMM/files/192650/SDVMM.zip)
