### ISSUE TITLE
Error on update

### ISSUE THREAD

**Issue by cristian43** [yuukiw/StardewValleyMM#8]
When open SDVMM and it tries to update it says:
update failed...

Something went wrong with the update.

and let my chose in retry or cancel but even if i press retry the same error pops..

i could update the SDVMM closing him and opening the update.bat, then after a few sec it pops the SDVMM 1.6c

and now i have another problem:

When i open the SDVMM v1.6c and it tries to update the smapi it says: "cannot read file from disk! Errorlevel: 0"

(sorry if i wrote something wrong...)

**Comment by yuukiw** [comment]
try to delete the update folder

**Comment by yuukiw** [comment]
could you test that file
[SDVMM.zip](https://github.com/yuukiw/StardewValleyMM/files/192650/SDVMM.zip)

**Comment by AndreG21** [comment]
it started to work but then it gives me this screen
![screenshot 6](https://cloud.githubusercontent.com/assets/18153861/14126729/bc14376a-f5d8-11e5-9bfd-cec40257f8d3.png)

**Comment by yuukiw** [comment]
Could you describe if something happened between it working and it now not working?

**Comment by AndreG21** [comment]
while it was working the commands would show just green text, but now i get a mixture of green and red text when i start it

(First)
![screenshot 9](https://cloud.githubusercontent.com/assets/18153861/14162443/9b6a4728-f6b1-11e5-9ea8-a1c81adfbc20.png)

(Second)
![screenshot 7](https://cloud.githubusercontent.com/assets/18153861/14162452/a9750790-f6b1-11e5-807e-2afd836145f6.png)

(Third)
![screenshot 11](https://cloud.githubusercontent.com/assets/18153861/14162458/b8da1996-f6b1-11e5-8394-620a75a95746.png)

**Comment by yuukiw** [comment]
the momvement mod seems to be corupted or missing the manifest

**Comment by yuukiw** [comment]
btw if you down own the game yet and are using an cracked version you could in theory switch over to gog = true. Which eliminates Steam out of the equation when launching.

**Comment by AndreG21** [comment]
Ok ,also while trying to deactivate certain mods to see if i can solve the problem, I found that .storm won't allow me to reactivate them.

**Comment by cristian43** [comment]
well, i've tryed with that link of 1.6c and when i started it, pops a extration windows that says it couldn't delete SDVMM, after closing it i opened the "update.bat", all works correctly and then sdvmm 1.6e opened, all settings were set atomaticaly and i was able to delete mods (modname.dll) from the list.
now, if i press "add SMAPI/XNB mod", select a xnb file and i cancel the "XNB selection" it pops an error that says it couldn't find the archive (i don't know if that is intentional but sounds like a bug)
and... apparently... that is all, 
it doesn't autoupdate but it download the update, so u can manually update it, and a little XNB bug (nothing important)
edit: i've tested that all in SDV ver 1.7
edit2: i found something else: if i add a mod (dll) i cant remove it until i close and re-open the SDVMM, and if i add an XNB i can't delete it and restore it's backup and i have to go to .ini folder,  remove the line in the SDVMM.ini with that specific mod and restore the backup manually

**Comment by yuukiw** [comment]
The message that appears when canceling out of the xnb Selektion is somewhat Intentionen but i need to Differentiat it more. 

The xnb deleting bug is known and i would fix it Asap the DLL one is new. 

But it could take a while since University just started again.

**Comment by cristian43** [comment]
yeah, no problem, if i found something else i'll let u know
